services:
  - type: web
    name: ssticer-deletor
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: RENDER_EXTERNAL_URL
        value: https://ssticer-deletor.onrender.com
